account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login_jp.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #会員ページ
    path('profile_jp/', views.profile, name='profile'),
    #プロフィール
    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/delete/', views.profile_delete, name='profile_delete'),
    #会員情報修正
    path('profile/user_info/', views.user_update, name='user_info'),
    #連絡先修正
    path('profile/address_update/', views.address_update, name='address_update'),
    #パスワード変更
    path('profile/password_update', views.password_update, name='password_update'),
    
    
]

faq/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.faq, name='faq'),   
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_list, name='shop_list'),
   
    path('search/', views.search, name='search'),
    path('<int:pk>/', views.shop_detail, name='shop_detail'),
    path('<int:pk>/like/', views.like_page, name='like_page'),
    path('<int:pk>/unlike/', views.unlike_page, name='unlike_page'),

    # レビュー
    path('review_list/', views.review_list, name='review_list'),
    path('review_read/', views.review_read, name='review_read'),
    path('review_create/', views.review_create, name='review_create'),
    path('review_update/', views.review_update, name='review_update'),
    path('review_delete/', views.review_delete, name='review_delete'),
    
    # お問い合わせ
    path('inquiry_list/', views.inquiry_list, name='inquiry_list'),
    path('inquiry_read/', views.inquiry_read, name='inquiry_read'),
    path('inquiry_create/', views.inquiry_create, name='inquiry_create'),
    path('inquiry_update/', views.inquiry_update, name='inquiry_update'),
    path('inquiry_delete/', views.inquiry_delete, name='inquiry_delete'),

    path('category/<str:slug>/', views.category_page),
    path('brand/<str:slug>/', views.brand_page),
    path('cart_list/', views.cart_list, name='cart_list'),
    path('<int:pk>/add_cart/', views.add_cart, name='add_cart'),

    # ショッピングカートAjax適用X
    #　path('<int:pk>/remove_cart/', views.remove_cart, name='remove_cart'),
    # path('plus_cart/<int:pk>/', views.cart_plus_btn, name='cart_plus_btn'),
    # path('minus_cart/<int:pk>/', views.cart_minus_btn, name='cart_minus_btn'),
    
    # ショッピングカートAjax適用
    path('plus-cart/', views.plus_cart, name='plus_cart'),
    path('minus-cart/', views.minus_cart, name='minus_cart'),
    path('delete-cart/', views.remove_cart, name='delete_cart'),
    path('<int:pk>/remove_cart/', views.remove_cart, name='remove_cart'),

    # お気に入り
    path('my_wish_list/', views.wish_list, name='wish_list'),

]

single_pages/urls.py
from django.urls import path
from . import views

app_name = 'single_pages'

urlpatterns = [
    path('', views.landing,  name='landing'),
    path('about/', views.about, name='about'),
   
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LUCY</title>

    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">
    

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'libs/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/style_star.css' %}">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'custom/css/custom.css' %}" type="text/css">
</head>
<body>

{% include 'base/nav.html' %}

{%block index %}
{% endblock %}
<div class="container">
    {% block main_area %}
    {% endblock %}
</div>


 
{% include 'base/footer.html' %}
{% include 'base/search.html' %}


<!-- Js Plugins -->
<script src="{% static 'libs/js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'libs/js/bootstrap.min.js' %}" ></script>
<script src="{% static 'libs/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'libs/js/mixitup.min.js' %}"></script>
<script src="{% static 'libs/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'libs/js/main.js' %}"></script>
<!-- custom js -->
<script src="{% static 'custom/js/reg.js' %}"></script>
<script src="{% static 'custom/js/valid.js' %}"></script>

<!-- javascript for review -->
{% block review_script %}{% endblock %}
<!--// javascript for review -->
<!-- javascript for inquiry -->
{% block inquiry_script %}{% endblock %}
<!--// javascript for inquiry -->
<!-- javascript for review_jp -->
{% block review_script_jp %}{% endblock %}
<!--// javascript for review_jp -->
<!-- javascript for inquiry_jp -->
{% block inquiry_script_jp %}{% endblock %}
<!--// javascript for inquiry_jp -->


{% block script %}{% endblock %}
</body>
</html>

templates/base/base_jp.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LUCY</title>

    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">
    

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'libs/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'libs/css/style_star.css' %}">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'custom/css/custom.css' %}" type="text/css">
</head>
<body>

{% include 'base/nav_jp.html' %}

{%block index %}
{% endblock %}
<div class="container">
    {% block main_area %}
    {% endblock %}
</div>


 
{% include 'base/footer.html' %}
{% include 'base/search_jp.html' %}


<!-- Js Plugins -->
<script src="{% static 'libs/js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'libs/js/bootstrap.min.js' %}" ></script>
<script src="{% static 'libs/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'libs/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'libs/js/mixitup.min.js' %}"></script>
<script src="{% static 'libs/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'libs/js/main.js' %}"></script>
<!-- custom js -->
<script src="{% static 'custom/js/reg.js' %}"></script>
<script src="{% static 'custom/js/valid.js' %}"></script>

<!-- javascript for review -->
{% block review_script %}{% endblock %}
<!--// javascript for review -->
<!-- javascript for inquiry -->
{% block inquiry_script %}{% endblock %}
<!--// javascript for inquiry -->
<!-- javascript for review_jp -->
{% block review_script_jp %}{% endblock %}
<!--// javascript for review_jp -->
<!-- javascript for inquiry_jp -->
{% block inquiry_script_jp %}{% endblock %}
<!--// javascript for inquiry_jp -->


{% block script %}{% endblock %}
</body>
</html>

templates/base/error.html
<!-- 상태 문구-->
{% if messages %}
{% for message in messages %}
      <div{% if message.tags %} class="alert alert-{{ message.tags }} alert-auto-dismissible text-center" {% endif %}>{{ message }}</div>
{% endfor %}
{% endif %}
<script>
    //3초 후 상태 문구 창 사라짐
    window.setTimeout(function() {
      $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
          $(this).remove();
      });
  }, 1000);
  </script>

templates/base/inquiry_script.html
{% block inquiry_script %}
<script>
    // 문의 정보
    function get_inquiry(inquiry_id) {
        console.log('get_inquiry', inquiry_id)
        $.ajax({
            type: 'GET',
            url: '{% url 'shop:inquiry_read' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'inquiry_id': inquiry_id,
            },
            success: function (response) {
                console.log(response)
                let content = response['inquiry']['content'];

                $('#inquiryDone').addClass('d-none');
                $('#inquiryForm textarea[name=content]').val(content);
                $('#inquiryForm').removeClass('d-none');

                $('#btnInquiryFormCreate').addClass('d-none');
                $('#btnInquiryFormUpdate').data('inquiry-id', inquiry_id);
                $('#btnInquiryFormUpdate').removeClass('d-none');
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    }

    // 문의 삭제
    function delete_inquiry(inquiry_id) {
        let answer = window.confirm('문의를 삭제하시겠습니까?');
        if (answer) {
            $.ajax({
                type: 'POST',
                url: '{% url 'shop:inquiry_delete' %}',
                dataType: 'JSON',
                data: {
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                    'inquiry_id': inquiry_id,
                },
                success: function (response) {
                    $('#inquiryForm textarea[name=content]').val('');
                    get_inquiry_list();
                },
                error: function(request, status, error){
                    alert(error);
                }
            });
        }
    }

    // 문의 목록 가져오기
    function get_inquiry_list() {
        let inquiry_done = false;

        $.ajax({
            type: 'GET',
            url: '{% url 'shop:inquiry_list' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'product_id': '{{ product.id }}',
            },
            success: function (response) {
                $('#inquiryDone').removeClass('d-none');
                $('#inquiryForm').addClass('d-none');
                $('#btnInquiryFormCreate').removeClass('d-none');
                $('#btnInquiryFormUpdate').addClass('d-none');

                let row = '';
                $('#inquiry_list').empty();
                for (let i=0; i < response['inquiry_list'].length; i++) {
                    let inquiry_id = response['inquiry_list'][i]['inquiry_id'];
                    let profile_img = response['inquiry_list'][i]['profile_img'];
                    let nickname = response['inquiry_list'][i]['nickname'];
                    let yyyyMMdd = response['inquiry_list'][i]['created_at'].split('T')[0];
                    let hhmmss = response['inquiry_list'][i]['created_at'].split('T')[1].split('.')[0];
                    let created_at = yyyyMMdd + ' ' + hhmmss
                    let content = response['inquiry_list'][i]['content'];
                    let user_id = response['inquiry_list'][i]['user_id'];
                    let admin_answer = response['inquiry_list'][i]['admin_answer'];
                    let admin_answered = response['inquiry_list'][i]['admin_answered'];


                    row += '<div class="media mb-4" id="inquiry-{{ inquiry.pk }}">';

                    if (profile_img) {
                        row += '<img class="d-flex mr-3 rounded-circle" src="/media/' + profile_img + '" id="userImg" class="mt-3" style="width:50px; height: 50px; border-radius: 50%; border: 1px solid #ccc;">';
                    } else {
                        row += '<img class="d-flex mr-3 rounded-circle" src="https://via.placeholder.com/50">';
                    }

                    row += '<div class="media-body">';
                    row += '<h5 class="mt-0">' + nickname + '&nbsp;&nbsp;';
                    row += '<small class="text-muted">' + created_at + '</small>';

                    if (user_id == '{{ user.id }}') {
                        // 관리자 답변이 달렸다면 유저는 수정 기능 이용 불가
                        if (admin_answered) {
                            row += '<button type="button" class="btn btn-sm btn-danger ml-2" onclick="delete_inquiry(' + inquiry_id + ')">삭제</button>'
                        } else {
                            row += '<button type="button" class="btn btn-sm btn-warning ml-2" onclick="get_inquiry(' + inquiry_id + ')">수정</button>'
                            row += '<button type="button" class="btn btn-sm btn-danger ml-2" onclick="delete_inquiry(' + inquiry_id + ')">삭제</button>'    
                        }
                        inquiry_done = true;
                    }

                    row += '</h5>';
                    row += '<p>' + content + '</p>';
                    // 관리자 답변이 달렸다면
                    if (admin_answered) {
                        row += '<div class="card border-light mb-3">';
                        row += '<div class="card-header">' + 'From: LUCY' + '</div>';
                        row += '<div class="card-body">';
                        row +=  '<p class="card-text">' + admin_answer + '</p>';
                        row +=  '</div>';
                        row +=  '</div>';
                        row +=  '</div>';
                    // 관리자 답변이 없다면      
                    } else {
                        row += '<div class="card border-light mb-3">';
                            row += '<div class="card-header">' + 'From: LUCY' + '</div>';
                            row += '<div class="card-body">';
                            row +=  '<p class="card-text">' + '미답변 상태입니다.' + '</p>';
                            row +=  '</div>';
                            row +=  '</div>';
                            row +=  '</div>';
                        }    
                    row += '</div>';
                    row += '</div>';
                }

                $('#inquiry_list').html(row);

                // 문의를 등록한 경우
                if (inquiry_done) {
                    $('#inquiryForm').removeClass('d-none');
                    $('#inquiryDone').removeClass('d-none');
                    $('#btnInquiryFormCreate').removeClass('d-none');
                }
                // 문의를 등록하지 않은 경우
                else {
                    $('#inquiryForm').removeClass('d-none');
                    $('#inquiryDone').addClass('d-none');
                    $('#btnInquiryFormCreate').removeClass('d-none');
                }
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    }

    // 문의 목록
    get_inquiry_list();

    // 문의 등록
    $('#btnInquiryFormCreate').on('click', function(e) {
        e.preventDefault();
        let content = $('#inquiryForm textarea[name=content]').val();

        if (!content) {
            alert('후기를 남겨주세요.');
            return false;
        }

        $.ajax({
            type: 'POST',
            url: '{% url 'shop:inquiry_create' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'product_id': '{{ product.id }}',
                'content': content,
            },
            success: function (response) {
                if (response.result == 'ok') {
                    $('#inquiryForm textarea[name=content]').val('');
                    get_inquiry_list();
                    $('#inquiryDone').removeClass('d-none');
                    $('#inquiryForm').addClass('d-none');
                }
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    })

    // 문의 수정
    $('#btnInquiryFormUpdate').on('click', function() {
        let inquiry_id = $(this).data('inquiry-id');
        let content = $('#inquiryForm textarea[name=content]').val();
        console.log(content)

        if (!content) {
            alert('후기를 남겨주세요.');
            return false;
        }

        $.ajax({
            type: 'POST',
            url: '{% url 'shop:inquiry_update' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'inquiry_id': inquiry_id,
                'content': content,
            },
            success: function (response) {
                $('#inquiryForm textarea[name=content]').val('');
                get_inquiry_list();
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    })
</script>
{% endblock %}

templates/base/inquiry_script_jp.html
{% block inquiry_script %}
<script>
    // お問い合わ情報
    function get_inquiry(inquiry_id) {
        console.log('get_inquiry', inquiry_id)
        $.ajax({
            type: 'GET',
            url: '{% url 'shop:inquiry_read' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'inquiry_id': inquiry_id,
            },
            success: function (response) {
                console.log(response)
                let content = response['inquiry']['content'];

                $('#inquiryDone').addClass('d-none');
                $('#inquiryForm textarea[name=content]').val(content);
                $('#inquiryForm').removeClass('d-none');

                $('#btnInquiryFormCreate').addClass('d-none');
                $('#btnInquiryFormUpdate').data('inquiry-id', inquiry_id);
                $('#btnInquiryFormUpdate').removeClass('d-none');
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    }

    // お問い合わせ削除
    function delete_inquiry(inquiry_id) {
        let answer = window.confirm('削除しますか？');
        if (answer) {
            $.ajax({
                type: 'POST',
                url: '{% url 'shop:inquiry_delete' %}',
                dataType: 'JSON',
                data: {
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                    'inquiry_id': inquiry_id,
                },
                success: function (response) {
                    $('#inquiryForm textarea[name=content]').val('');
                    get_inquiry_list();
                },
                error: function(request, status, error){
                    alert(error);
                }
            });
        }
    }

    // お問い合わせリスト
    function get_inquiry_list() {
        let inquiry_done = false;

        $.ajax({
            type: 'GET',
            url: '{% url 'shop:inquiry_list' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'product_id': '{{ product.id }}',
            },
            success: function (response) {
                $('#inquiryDone').removeClass('d-none');
                $('#inquiryForm').addClass('d-none');
                $('#btnInquiryFormCreate').removeClass('d-none');
                $('#btnInquiryFormUpdate').addClass('d-none');

                let row = '';
                $('#inquiry_list').empty();
                for (let i=0; i < response['inquiry_list'].length; i++) {
                    let inquiry_id = response['inquiry_list'][i]['inquiry_id'];
                    let profile_img = response['inquiry_list'][i]['profile_img'];
                    let nickname = response['inquiry_list'][i]['nickname'];
                    let yyyyMMdd = response['inquiry_list'][i]['created_at'].split('T')[0];
                    let hhmmss = response['inquiry_list'][i]['created_at'].split('T')[1].split('.')[0];
                    let created_at = yyyyMMdd + ' ' + hhmmss
                    let content = response['inquiry_list'][i]['content'];
                    let user_id = response['inquiry_list'][i]['user_id'];
                    let admin_answer = response['inquiry_list'][i]['admin_answer'];
                    let admin_answered = response['inquiry_list'][i]['admin_answered'];


                    row += '<div class="media mb-4" id="inquiry-{{ inquiry.pk }}">';

                    if (profile_img) {
                        row += '<img class="d-flex mr-3 rounded-circle" src="/media/' + profile_img + '" id="userImg" class="mt-3" style="width:50px; height: 50px; border-radius: 50%; border: 1px solid #ccc;">';
                    } else {
                        row += '<img class="d-flex mr-3 rounded-circle" src="https://via.placeholder.com/50">';
                    }

                    row += '<div class="media-body">';
                    row += '<h5 class="mt-0">' + nickname + '&nbsp;&nbsp;';
                    row += '<small class="text-muted">' + created_at + '</small>';

                    if (user_id == '{{ user.id }}') {
                        // 管理者の回答がある場合、ユーザーは修正機能を利用できません
                        if (admin_answered) {
                            row += '<button type="button" class="btn btn-sm btn-danger ml-2" onclick="delete_inquiry(' + inquiry_id + ')">削除</button>'
                        } else {
                            row += '<button type="button" class="btn btn-sm btn-warning ml-2" onclick="get_inquiry(' + inquiry_id + ')">修整</button>'
                            row += '<button type="button" class="btn btn-sm btn-danger ml-2" onclick="delete_inquiry(' + inquiry_id + ')">削除</button>'    
                        }
                        inquiry_done = true;
                    }

                    row += '</h5>';
                    row += '<p>' + content + '</p>';
                    // 管理者の回答ある
                    if (admin_answered) {
                        row += '<div class="card border-light mb-3">';
                        row += '<div class="card-header">' + 'From: LUCY' + '</div>';
                        row += '<div class="card-body">';
                        row +=  '<p class="card-text">' + admin_answer + '</p>';
                        row +=  '</div>';
                        row +=  '</div>';
                        row +=  '</div>';
                    // 管理者の回答なし      
                    } else {
                        row += '<div class="card border-light mb-3">';
                            row += '<div class="card-header">' + 'From: LUCY' + '</div>';
                            row += '<div class="card-body">';
                            row +=  '<p class="card-text">' + '返信がまだ来ていません。' + '</p>';
                            row +=  '</div>';
                            row +=  '</div>';
                            row +=  '</div>';
                        }    
                    row += '</div>';
                    row += '</div>';
                }

                $('#inquiry_list').html(row);

                //お問い合わせを登録した場合
                if (inquiry_done) {
                    $('#inquiryForm').removeClass('d-none');
                    $('#inquiryDone').removeClass('d-none');
                    $('#btnInquiryFormCreate').removeClass('d-none');
                }
                //お問い合わせを登録してない場合
                else {
                    $('#inquiryForm').removeClass('d-none');
                    $('#inquiryDone').addClass('d-none');
                    $('#btnInquiryFormCreate').removeClass('d-none');
                }
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    }

    // お問い合わせリスト
    get_inquiry_list();

    // 登録
    $('#btnInquiryFormCreate').on('click', function(e) {
        e.preventDefault();
        let content = $('#inquiryForm textarea[name=content]').val();

        if (!content) {
            alert('お問い合わせください。');
            return false;
        }

        $.ajax({
            type: 'POST',
            url: '{% url 'shop:inquiry_create' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'product_id': '{{ product.id }}',
                'content': content,
            },
            success: function (response) {
                if (response.result == 'ok') {
                    $('#inquiryForm textarea[name=content]').val('');
                    get_inquiry_list();
                    $('#inquiryDone').removeClass('d-none');
                    $('#inquiryForm').addClass('d-none');
                }
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    })

    // 修正
    $('#btnInquiryFormUpdate').on('click', function() {
        let inquiry_id = $(this).data('inquiry-id');
        let content = $('#inquiryForm textarea[name=content]').val();
        console.log(content)

        if (!content) {
            alert('お問い合わせください。');
            return false;
        }

        $.ajax({
            type: 'POST',
            url: '{% url 'shop:inquiry_update' %}',
            dataType: 'JSON',
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'inquiry_id': inquiry_id,
                'content': content,
            },
            success: function (response) {
                $('#inquiryForm textarea[name=content]').val('');
                get_inquiry_list();
            },
            error: function(request, status, error){
                alert(error);
            }
        });
    })
</script>
{% endblock %}

templates/base/nav.html
{% load static %}
  <header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__nav">
                            <ul class="navbar-nav ml-auto">
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                 <a class="nav-link" href="{% url 'account:logout' %}">Sign Out</a>
                                </li>
                                {% else %}
                                {% include 'base/modal.html'%}
                                <li class="nav-item">
                                  <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Sign In</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                        <div class="header__top__hover">
                            <span>KOR <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>
                                    <a href="#"> KOR</a>
                                </li>
                                <li>
                                    <a href="#">JPN</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="/">LUCY</a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="{% if current_page == 'landing' %}active{% endif %}"><a href="/">Home</a></li>
                        <li class="{% if current_page == 'shop' %}active{% endif %}"><a href="{% url 'shop:shop_list' %}">Shop</a></li>
                        <li class="{% if current_page == 'about' %}active{% endif %}"><a href="{% url 'single_pages:about' %}">About</a></li>
                        <li class="{% if current_page == 'faq' %}active{% endif %}"><a href="{% url 'faq' %}">FAQs</a></li>
                        <li class="{% if current_page == 'my' %}active{% endif %}"><a href="{% url 'account:profile' %}">My Account</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    {% if user.is_authenticated %}
                    <a href="#" class="search-switch"><img src="{% static 'libs/img/icons/search.png' %}" alt=""></a>
                    <a href="/shop/my_wish_list/"><img src="{% static 'libs/img/icons/heart.png' %}" alt=""></a>
                    <a href="/shop/cart_list/"><img src="{% static 'libs/img/icons/cart.png' %}" alt=""></a>
                    {% else %}
                    <a href="#" class="search-switch"><img src="{% static 'libs/img/icons/search.png' %}" alt=""></a>
                    <a href="{% url 'account:login' %}"><img src="{% static 'libs/img/icons/heart.png' %}" alt=""></a>
                    <a href="{% url 'account:login' %}"><img src="{% static 'libs/img/icons/cart.png' %}" alt=""></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

templates/base/search.html
{% load static %}
<div class="search-model" style=" opacity: 0.88;">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" action="{% url 'shop:search' %}">
            <input name="q" type="text" id="search-input" placeholder="검색어를 입력해주세요....">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">검색</button>
        </form>
    </div>
</div>