faq/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.faq, name='faq'),   
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_list, name='shop_list'),
   
    path('search/', views.search, name='search'),
    path('<int:pk>/', views.shop_detail, name='shop_detail'),
    path('<int:pk>/like/', views.like_page, name='like_page'),
    path('<int:pk>/unlike/', views.unlike_page, name='unlike_page'),

    # レビュー
    path('review_list/', views.review_list, name='review_list'),
    path('review_read/', views.review_read, name='review_read'),
    path('review_create/', views.review_create, name='review_create'),
    path('review_update/', views.review_update, name='review_update'),
    path('review_delete/', views.review_delete, name='review_delete'),
    
    # お問い合わせ
    path('inquiry_list/', views.inquiry_list, name='inquiry_list'),
    path('inquiry_read/', views.inquiry_read, name='inquiry_read'),
    path('inquiry_create/', views.inquiry_create, name='inquiry_create'),
    path('inquiry_update/', views.inquiry_update, name='inquiry_update'),
    path('inquiry_delete/', views.inquiry_delete, name='inquiry_delete'),

    path('category/<str:slug>/', views.category_page),
    path('brand/<str:slug>/', views.brand_page),
    path('cart_list/', views.cart_list, name='cart_list'),
    path('<int:pk>/add_cart/', views.add_cart, name='add_cart'),

    # ショッピングカートAjax適用X
    #　path('<int:pk>/remove_cart/', views.remove_cart, name='remove_cart'),
    # path('plus_cart/<int:pk>/', views.cart_plus_btn, name='cart_plus_btn'),
    # path('minus_cart/<int:pk>/', views.cart_minus_btn, name='cart_minus_btn'),
    
    # ショッピングカートAjax適用
    path('plus-cart/', views.plus_cart, name='plus_cart'),
    path('minus-cart/', views.minus_cart, name='minus_cart'),
    path('delete-cart/', views.remove_cart, name='delete_cart'),
    path('<int:pk>/remove_cart/', views.remove_cart, name='remove_cart'),

    # お気に入り
    path('my_wish_list/', views.wish_list, name='wish_list'),

]

shop/models.py
from django.db import models
from account.models import User
from django.db.models import Avg


# カテゴリー
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


# ブランド
class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True)
    logo_img = models.ImageField(upload_to='shop/brands/%Y/%m/%d/', null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/brand/{self.slug}/'


# 商品
class Product(models.Model):
    signature_img = models.ImageField(verbose_name="商品イメージ",upload_to='shop/images/%Y/%m/%d/')
    title = models.CharField(verbose_name="商品名", max_length=30)  
    price = models.IntegerField(verbose_name="価格", default=0)  
    qty = models.PositiveSmallIntegerField(verbose_name="カート商品", null=False, default=1)  
    info = models.TextField(verbose_name="商品詳細", max_length=200, null=False)  
    like_count = models.IntegerField(verbose_name="お気に入り数", default=0)  
    created_at = models.DateTimeField(verbose_name="登録日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="修正時間", auto_now=True)
    category = models.ManyToManyField(
        Category, blank=True, verbose_name="カテゴリー")
    brand = models.ForeignKey(
        Brand, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="ブランド")

    def __str__(self):
        return f'[{self.pk}] {self.title}'

    def get_absolute_url(self):
        return f'/shop/{self.pk}/'

    def average_review(self):  # レビュー評価平均
        reviews = Review.objects.filter(product=self).aggregate(average=Avg('rate'))
        avg = 0
        if reviews['average'] is not None:
            avg = round(float(reviews['average']), 2)
        return avg

    def count_review(self):  # レビュー数
        count_review = Review.objects.filter(product=self).count()
        return count_review

    @property  # レビュー整列
    def get_reviews(self):
        return self.reviews.all().order_by('-created_at')


# お気に入り
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="会員")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="商品")

    def __str__(self):
        return f'{self.product} - {self.user}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#like-{self.pk}'


# レビュー
class Review(models.Model):
    content = models.TextField(verbose_name="内容")
    created_at = models.DateTimeField(verbose_name="登録日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="修正時間", auto_now=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name="会員")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="商品")
    rate = models.FloatField(verbose_name="評価")

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'[{self.pk}][{self.product.title}] - {self.user.nickname} :{self.rate}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}{self.pk}'


# お問い合わせ
class Inquiry(models.Model):
    content = models.TextField(verbose_name="内容")
    answer = models.TextField(verbose_name="返信", null=True)
    answered = models.BooleanField(verbose_name="返信確認", default=False)
    created_at = models.DateTimeField(verbose_name="登録日時", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="登修正日時", auto_now=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name="会員")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="商品")

    class Meta:
        ordering = ('-created_at',)
        verbose_name_plural = 'Inquiries'

    def __str__(self):
        return f'[{self.pk}][{self.product.title}] - 問い合わせ者 : {self.user.nickname}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}{self.pk}'


# ショッピングカート
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="会員")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="商品")
    product_qty = models.IntegerField(verbose_name="商品数量")
    created_at = models.DateTimeField(verbose_name="登録日時", auto_now_add=True)

    def __str__(self):
        return f'[{self.pk}] 商品-{self.product.title} | 会員-{self.user.nickname} | 数量 -{self.product_qty}'

    # 商品の数量に合わせて金額変更
    def sub_total(self):
        return format(self.product.price * self.product_qty, ',')

shop/forms.py
from django import forms
from .models import Review, Inquiry

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('content', 'rate',)

class EditReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('content', 'rate',)
        
class InquiryForm(forms.ModelForm):

    class Meta:
        model = Inquiry
        fields = ('content',)

class EditInquiryForm(forms.ModelForm):

    class Meta:
        model = Inquiry
        fields = ('content',)

shop/views.py
import json
from datetime import datetime
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.core.paginator import Paginator
from django.core import serializers
from django.contrib import messages
from account.models import User
from .models import Inquiry, Product, Category, Brand, Like, Cart, Review
from .forms import ReviewForm, InquiryForm


def shop_list(request):
    product_list = Product.objects.order_by('-created_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(product_list, 6)
    object_list = paginator.get_page(page)

    context = {
        'product_list': object_list,
        'brands': Brand.objects.all(),
        'categories': Category.objects.all(),
        'no_category_product_count': Product.objects.filter(category=None).count(),
        'no_brand_product_count': Product.objects.filter(brand=None).count(),
        'current_page': 'shop',
    }

    return render(request, "shop/shop_list_jp.html", context)

# 商品詳細
def shop_detail(request, pk):
    product = Product.objects.get(id=pk)
    review_form = ReviewForm
    inquiry_form = InquiryForm
    like_count = Like.objects.filter(product=pk).count()
    like = Like.objects.filter(user=request.user.id, product=pk)
    review = Review.objects.filter(user=request.user.id, product=pk)

    return render(
        request,
        'shop/shop_detail_jp.html',
        {
            'product': product,
            'review_form': review_form,
            'inquiry_form': inquiry_form,
            'like_count': like_count,
            'like': like,
            'review': review,
            'current_page': 'shop',
        }
    )

# 商品検索
def search(request):
    q=request.GET['q']
    data = Product.objects.filter(title__icontains=q).order_by('-id')
    page = request.GET.get('page', 1)
    paginator = Paginator(data, 6)
    object_list = paginator.get_page(page)
    return render(request,
                  'shop/shop_search_list_jp.html',
                  {
                      'data': object_list,
                      'brands': Brand.objects.all(),
                      'categories': Category.objects.all(),
                      'no_category_product_count': Product.objects.filter(category=None).count(),
                      'no_brand_product_count': Product.objects.filter(brand=None).count(),
                      'current_page': 'shop',
                  }
            )

# レビュー登録
"""
def review_page(request, pk):
    if request.method == 'POST':
        product = Product.objects.get(id=pk)
        rating = request.POST['rating']
        content = request.POST['content']

        obj = Review.objects.create(
            content=content,
            rate=rating,
            user=request.user,
            product=product,
        )
        obj.save()
        return redirect('shop:shop_detail', pk)
"""


# レビューリスト
@csrf_protect
def review_list(request):
    if request.method == 'GET':
        product_id = request.GET.get('product_id')
        review_list = Review.objects.filter(product_id=product_id)

        review_dict = []
        for review in review_list:
            user = User.objects.get(pk=review.user.id)

            review_arr = {
                'rate': review.rate,
                'content': review.content,
                'created_at': review.created_at,
                'profile_img': str(user.profile_img),
                'nickname': user.nickname,
                'user_id': user.id,
                'review_id': review.id,
            }
            review_dict.append(review_arr)

        return JsonResponse({'review_list': review_dict})


# レビュー情報
@csrf_protect
def review_read(request):
    if request.method == 'GET':
        review_id = request.GET.get('review_id')
        review = Review.objects.get(pk=review_id)

        review_arr = {
            'rate': review.rate,
            'content': review.content,
            'review_id': review.id,
        }
        return JsonResponse({'review': review_arr})


# レビュー登録
@csrf_protect
def review_create(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        rating = request.POST.get('rating')
        content = request.POST.get('content')
        product = Product.objects.get(id=product_id)

        obj = Review.objects.create(
            content=content,
            rate=rating,
            user=request.user,
            product=product,
        )
        obj.save()
        return JsonResponse({'result': 'ok'})


# レビュー修正
@csrf_protect
def review_update(request):
    if request.method == 'POST':
        review_id = request.POST.get('review_id')
        rating = request.POST.get('rating')
        content = request.POST.get('content')
        review = Review.objects.get(pk=review_id)
        review.rate = rating
        review.content = content
        review.save()
        return JsonResponse({'result': 'ok'})


# レビュー削除
@csrf_protect
def review_delete(request):
    if request.method == 'POST':
        review_id = request.POST.get('review_id')
        review = Review.objects.get(pk=review_id)
        review.delete()
        return JsonResponse({'result': 'ok'})


# お問い合わせリスト
@csrf_protect
def inquiry_list(request):
    if request.method == 'GET':
        product_id = request.GET.get('product_id')
        inquiry_list = Inquiry.objects.filter(product_id=product_id)

        inquiry_dict = []
        for inquiry in inquiry_list:
            user = User.objects.get(pk=inquiry.user.id)

            inquiry_arr = {
                'content': inquiry.content,
                'created_at': inquiry.created_at,
                'profile_img': str(user.profile_img),
                'nickname': user.nickname,
                'user_id': user.id,
                'inquiry_id': inquiry.id,
                'admin_answer' : inquiry.answer,
                'admin_answered' : inquiry.answered,
            }
            inquiry_dict.append(inquiry_arr)

        return JsonResponse({'inquiry_list': inquiry_dict})


# お問い合わせ情報
@csrf_protect
def inquiry_read(request):
    if request.method == 'GET':
        inquiry_id = request.GET.get('inquiry_id')
        inquiry = Inquiry.objects.get(pk=inquiry_id)

        inquiry_arr = {
            'content': inquiry.content,
            'inquiry_id': inquiry.id,
        }
        return JsonResponse({'inquiry': inquiry_arr})


# お問い合わせ登録
@csrf_protect
def inquiry_create(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        content = request.POST.get('content')
        product = Product.objects.get(id=product_id)

        obj = Inquiry.objects.create(
            content=content,
            user=request.user,
            product=product,
        )
        obj.save()
        return JsonResponse({'result': 'ok'})


# お問い合わせ修正
@csrf_protect
def inquiry_update(request):
    if request.method == 'POST':
        inquiry_id = request.POST.get('inquiry_id')
        content = request.POST.get('content')
        inquiry = Inquiry.objects.get(pk=inquiry_id)
        inquiry.content = content
        inquiry.save()
        return JsonResponse({'result': 'ok'})


# お問い合わせ削除
@csrf_protect
def inquiry_delete(request):
    if request.method == 'POST':
        inquiry_id = request.POST.get('inquiry_id')
        inquiry = Inquiry.objects.get(pk=inquiry_id)
        inquiry.delete()
        return JsonResponse({'result': 'ok'})




"""
# お問い合わせ登録

def inquiry_page(request, pk):
    product = Product.objects.get(id=pk)
    category = Category.objects.all()
    no_category_product_count = Product.objects.filter(category=None).count()
    #    review_form = ReviewForm
    like_count = Like.objects.filter(product=pk).count()
    inquiry_form = InquiryForm
    if request.method == 'POST':
        inquiry_form = InquiryForm(request.POST)
        content = request.POST['content']

        obj = Inquiry.objects.create(
            content=content,
            user=request.user,
            product=product,
        )
        obj.save()
        return redirect('shop:shop_detail', pk)
"""

"""
@csrf_protect
def inquiry_list(request):
    if request.method == 'GET':
        pk = request.GET.get('pk')

        inquiry_list = Inquiry.objects.filter(product=pk)

        inquiry_dict = []
        for inquiry in inquiry_list:
            user = User.objects.get(pk=inquiry.user.id)

            inquiry_arr = {
                'content': inquiry.content,
                'created_at': inquiry.created_at,
                'profile_img': str(user.profile_img),
                'nickname': user.nickname,
                'answer': inquiry.answer,
                'answered': inquiry.answered,
            }
            inquiry_dict.append(inquiry_arr)

        return JsonResponse({'inquiry_list': inquiry_dict})


@csrf_protect
def inquiry_create(request):
    if request.method == 'POST':
        pk = request.POST.get('pk')
        product = Product.objects.get(id=pk)
        content = request.POST['content']

        obj = Inquiry.objects.create(
            content=content,
            user=request.user,
            product=product,
        )
        obj.save()
        return JsonResponse({'result': 'ok'})


@csrf_protect
def inquiry_delete(request):
    if request.method == 'POST':
        pk = request.POST.get('pk')
        product = Product.objects.get(id=pk)
        content = request.POST['content']

        obj = Inquiry.objects.get_or_create(
            content=content,
            user=request.user,
            product=product,
        )
        obj.delete()
        return JsonResponse({'result': 'ok'})
"""

# いいね　登録
def like_page(request, pk):
    product = Product.objects.get(id=pk)
    review_form = ReviewForm
    inquiry_form = InquiryForm
    like = Like.objects.create(product=product, user=request.user)
    product.like_count += 1
    product.save()

templates/shop/cart_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}
{% block main_area %}
<script src="{% static 'libs/js/jquery-3.6.3.min.js' %}"></script>

<div class="card mb-4">
    <div class="card-body text-center">
      <h4><i class="fa fa-shopping-cart mr-2"></i>장바구니</h4>
    </div>
  </div>
  {% include 'base/error.html' %}
<div class="row cart_data">
    <div class="col-md-8 mt-4 mb-4">
        {% if cart_list %}
        {% for my_cart in cart_list %}
        <div class="media product_data">
            {% csrf_token %}
            <input type="hidden" value="{{my_cart.product.id}}" class="prod_id">
            <a href="/shop/{{my_cart.product.id}}/">
            <img src="{{ my_cart.product.signature_img.url }}" class="align-self-center mr-3" style="width:200px; height:200px">
            <div class="media-body">
                <h5 class="mt-0">{{my_cart.product.title}}</h5>
                <p>{{my_cart.product.brand}}</p>
            </a>
                <br />
                <div class="mt-5">
                    <br />
                    
                    <button class="btn btn-secondary btn-minus" id="decrease">
                        <i class="fa fa-minus"></i>
                    </button>
                    <input type="text" style="width: 3rem; border: none;" name="quantity" class="qty-input text-center" value="{{my_cart.product_qty}}">
                    <button class="btn btn-secondary btn-plus" id="increase">
                        <i class="fa fa-plus"></i>
                    </button>
                    <button class="btn btn-dark ml-3 btn-remove" style="float: right; color:#fff;"><i class="fa fa-trash"></i></button>
                    <span class="sub_total-{{my_cart.product.id}}" style="float: right; margin-top: 7px; color: black;">{{my_cart.sub_total | intcomma}}원</span>
                </div>
            </div>
        </div>
       
        <hr />
        {% endfor %}
                <!-- 페이징 -->
<ul class="pagination justify-content-center mt-5">
    <!-- 이전 페이지 -->
    {% if cart_list.has_previous %}<!-- 이전 페이지 있음 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ cart_list.previous_page_number }}">이전</a>
        </li>
    {% else %}<!-- 이전 페이지 없음 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}

    <!-- 페이지 리스트 -->
    {% for page_number in cart_list.paginator.page_range %}
        <!-- 현재 페이지를 기준으로 좌우 5개씩 보이도록 처리 -->
        {% if page_number >= cart_list.number|add:-5 and page_number <= cart_list.number|add:5 %}
            {% if page_number == cart_list.number %}<!-- 현재 페이지 번호와 같음 -->
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="/shop/cart_list?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% else %}<!-- 현재 페이지 번호와 다름 -->
                <li class="page-item">
                    <a class="page-link" href="/shop/cart_list?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}

    <!-- 다음 페이지 -->
    {% if cart_list.has_next %}<!-- 다음 페이지 있음 -->
        <li class="page-item">
            <a class="page-link" href="/shop/cart_list?page={{ cart_list.next_page_number }}">다음</a>
        </li>
    {% else %}<!-- 다음 페이지 없음 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
    {% endif %}
</ul>
<!--// 페이징 -->
    </div>
    <div class="col-md-4">
        {% if cart_list  %}
        <div class="card text-center">
            <div class="card-header font-weight-bold">
              결제할 상품 <small class="text-muted">총 {{cart_count}}개</small>
            </div>
            <div class="card-body">
                <p class="card-text text-left">상품 금액<span class="total-price" style="float: right;">{{ total_cart | intcomma}}원</span></p>
                <p class="card-text text-left">할인 금액 
                    <span class="sale-price" style="color: #37B6FF; float: right; margin-left: 10px;">-{{sale_price | intcomma}}원</span>
                    <span style="color: red; float: right;">15% SAVE</span>
                </p>
                <hr />
                <p class="card-text text-left font-weight-bold">결제 금액<span class="calculate" style="float: right;">{{ cart_sum | intcomma}}원</span></p>
            </div>
            <div class="card-footer text-dark">
                <a href="#" class="btn btn-primary" style="width: 320px;">결제하기</a>
            </div>
        </div>
        {% endif %}
    </div>
        {% else %}
        <div class="card mb-5" style="width: 70rem;">
            <div class="card-body">
              <h5 class="card-title">장바구니 상품</h5>
              <h6 class="card-subtitle mb-2 text-muted"></h6>
              <br />
              <p class="card-text">장바구니에 아무것도 담겨져 있지 않습니다.</p>
              <a href="{% url 'shop:shop_list' %}" class="btn btn-primary">스토어로 이동하기</a>
            </div>
          </div>
    {% endif %}

    


        </div>
</div>
<script>
    $(document).ready(function() {
        $('.btn-minus').click(function(e) {
            e.preventDefault();
            var inc_value = $(this).closest('.product_data').find('.qty-input').val();
            var value = parseInt(inc_value, 10);
            value = isNaN(value) ? 0: value;
            if(value > 1) {
                value--;
                $(this).closest('.product_data').find('.qty-input').val(value);
            }

        });
        $('.btn-plus').click(function(e) {
            e.preventDefault();
            var inc_value = $(this).closest('.product_data').find('.qty-input').val();
            var value = parseInt(inc_value, 10);
            value = isNaN(value) ? 0: value;
            if(value < 10) {
                value++;
                $(this).closest('.product_data').find('.qty-input').val(value);
            }
        });
    });

    //숫자 가격 표시 함수
    function priceToString(price) {
        return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
    }

    //plusBtn
    $('.btn-plus').click(function (e) {
        e.preventDefault();

        var product_id = $(this).closest('.product_data').find('.prod_id').val();
        var product_qty = $(this).closest('.product_data').find('.qty-input').val();
        var token = $('input[name=csrfmiddlewaretoken]').val()
        $.ajax({
            method: "POST",
            url: '{% url 'shop:plus_cart' %}',
            dataType: 'JSON',
            data: {
                'product_id':product_id,
                'product_qty':product_qty,
                csrfmiddlewaretoken: token

            },
            success: function(response) {
               var sub_total = priceToString(response.prod_price);
               var total_price = priceToString(response.total_price);
               var sale_price = priceToString(response.sale_price);
               var calculate_price = priceToString(response.calculate);

               $('.sub_total-' + product_id).text( sub_total + '원')
               $('.total-price').text( total_price + '원')
               $('.sale-price').text( '-' + sale_price + '원')
               $('.calculate').text(calculate_price + '원')
               

                
            }
        })
    })

     //minusBtn
     $('.btn-minus').click(function (e) {
        e.preventDefault();

        var product_id = $(this).closest('.product_data').find('.prod_id').val();
        var product_qty = $(this).closest('.product_data').find('.qty-input').val();
        var token = $('input[name=csrfmiddlewaretoken]').val()
        $.ajax({
            method: "POST",
            url: '{% url 'shop:minus_cart' %}',
            dataType: 'JSON',
            data: {
                'product_id':product_id,
                'product_qty':product_qty,
                csrfmiddlewaretoken: token

            },
            success: function(response) {
               var sub_total = priceToString(response.prod_price);
               var total_price = priceToString(response.total_price);
               var sale_price = priceToString(response.sale_price);
               var calculate_price = priceToString(response.calculate);
               
               $('.sub_total-' + product_id).text( sub_total + '원')
               $('.total-price').text( total_price + '원')
               $('.sale-price').text( '-' + sale_price + '원')
               $('.calculate').text(calculate_price + '원')
                
            }
        })
    })

     //removeBtn
     $('.btn-remove').click(function (e) {
        e.preventDefault();

        var product_id = $(this).closest('.product_data').find('.prod_id').val();
        var token = $('input[name=csrfmiddlewaretoken]').val()
        $.ajax({
            method: "POST",
            url: '{% url 'shop:delete_cart' %}',
            dataType: 'JSON',
            data: {
                'product_id':product_id,
                csrfmiddlewaretoken: token

            },
            success: function(response) {
                location.reload();
            }
        })
    })


    
</script>

{% endblock  %}

templates/shop/my_wish_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}
{% block main_area %}
<div class="card mb-4">
    <div class="card-body text-center">
       <span class="font-weight-bold">{{user.nickname}}</span> 님의 위시 리스트
    </div>
</div>
<div class="col-lg-12">
    <div class="row">
    {% if wish_list  %}
        {% for wish in wish_list %}
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="product__item">
                <div class="card">
                    <a href="{{wish.product.get_absolute_url}}">
                        <img src="{{wish.product.signature_img.url}}" alt="" width=600 height=260 >
                     </a>
                     <div class="card-body">
                        <h6 class="card-title mt-2">{{wish.product.title}}<br />
                            <small class="text-muted">{{wish.product.brand}}</small></h6>
                        <h5 class="mb-3">{{ wish.product.price | intcomma}}원<span style="float: right; color: red;"><i class="fa fa-heart fa-2x"></i></span></h5>
                        
                     </div>
                </div>
             </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="row">

        <div class="col-lg-12">
            <div class="card mb-5" style="width: 70rem;">
                <div class="card-body">
                  <h5 class="card-title">위시 리스트</h5>
                  <h6 class="card-subtitle mb-2 text-muted"></h6>
                  <br />
                  <p class="card-text">좋아요를 누르신 상품이 없습니다.</p>
                  <a href="{% url 'shop:shop_list' %}" class="btn btn-primary">스토어로 이동하기</a>
                </div>
            </div>
        </div>
        </div>
    {% endif %}
    </div>
        <!-- 페이징 -->
<ul class="pagination justify-content-center mt-5 mb-5">
    <!-- 이전 페이지 -->
    {% if wish_list.has_previous %}<!-- 이전 페이지 있음 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ wish_list.previous_page_number }}">이전</a>
        </li>
    {% else %}<!-- 이전 페이지 없음 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}

    <!-- 페이지 리스트 -->
    {% for page_number in wish_list.paginator.page_range %}
        <!-- 현재 페이지를 기준으로 좌우 5개씩 보이도록 처리 -->
        {% if page_number >= wish_list.number|add:-5 and page_number <= wish_list.number|add:5 %}
            {% if page_number == wish_list.number %}<!-- 현재 페이지 번호와 같음 -->
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% else %}<!-- 현재 페이지 번호와 다름 -->
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}

    <!-- 다음 페이지 -->
    {% if wish_list.has_next %}<!-- 다음 페이지 있음 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ wish_list.next_page_number }}">다음</a>
        </li>
    {% else %}<!-- 다음 페이지 없음 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
    {% endif %}
</ul>
<!--// 페이징 -->
</div>
{% endblock %}